export { default as UserController } from '../user.controller';
export { default as SignupController } from '../signup.controller';
export { default as LoginController } from '../login.controller';
export { default as BookController } from '../book.controller';
export { default as GenreController } from '../genre.controller';
export { default as AuthorController } from '../author.controller';
export { default as BookShelfController } from '../bookshelf.controller';
export { default as RatingController } from '../rating.controller';
export { default as RecommendationController } from '../recommendation.controller';
